name: Trigger MobileAp Automation Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger MobileAp Automation Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               https://api.github.com/repos/QiuRRQ/MobileAp-API-Testing/actions/workflows/test.yml/dispatches \-d '{"ref":"main"}'
